### ISSUE TITLE
Problemn in build android apk

### ISSUE THREAD

**Issue by luispimenta** [alexandretok/ionic2-rating#2]
Hello, I added the component without any problems and I can use it, but when I try to build apk for android, I get the error:

`ionic build android --prod`

`[12:15:28]  ionic-app-script task: "build" 
[12:15:28]  Error: Template parse errors: Can't bind to 'numStars' since it isn't a known property of 'ion-rating'. 1. 
            If 'ion-rating' is an Angular component and it has 'numStars' input, then verify that it is part of this 
            module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' 
            of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the 
            '@NgModule.schemas' of this component. (" <ion-col col-9 > <ion-rating *ngIf="current_user_details" [ERROR 
            ->][numStars]="5" [readOnly]="true" [value]="current_user_details.owner_average_score"> </"): 
            ng:///app/src/pages/profile/profile.html@131:7 Can't bind to 'readOnly' 
            since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 
            'readOnly' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 
            'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow 
            any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-col col-9 > 
            <ion-rating *ngIf="current_user_details" [numStars]="5" [ERROR ->][readOnly]="true" 
            [value]="current_user_details.owner_average_score"> </ion-rating> "): 
            ng:///app/src/pages/profile/profile.html@131:22 Can't bind to 'value' 
            since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 
            'value' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 
            'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow 
            any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-rating 
            *ngIf="current_user_details" [numStars]="5" [readOnly]="true" [ERROR 
            ->][value]="current_user_details.owner_average_score"> </ion-rating> </ion-col> "): 
            ng:///app/src/pages/profile/profile.html@132:7 'ion-rating' is not a 
            known element: 1. If 'ion-rating' is an Angular component, then verify that it is part of this module. 2. If 
            'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this 
            component to suppress this message. (" </ion-col> <ion-col col-9 > [ERROR ->]<ion-rating 
            *ngIf="current_user_details" [numStars]="5" [readOnly]="true" [value]="cur"): 
            ng:///app/src/pages/profile/profile.html@130:6 Can't bind to 'numStars' 
            since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 
            'numStars' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 
            'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow 
            any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-col col-9> 
            <ion-rating *ngIf="current_user_details" [ERROR ->][numStars]="5" [readOnly]="true" 
            [value]="current_user_details.assignee_average_score"> <"): 
            ng:///app/src/pages/profile/profile.html@142:6 Can't bind to 'readOnly' 
            since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 
            'readOnly' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 
            'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow 
            any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-col col-9> 
            <ion-rating *ngIf="current_user_details" [numStars]="5" [ERROR ->][readOnly]="true" 
            [value]="current_user_details.assignee_average_score"> </ion-rating> "): 
            ng:///app/src/pages/profile/profile.html@142:21 Can't bind to 'value' 
            since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 
            'value' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 
            'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow 
            any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-rating 
            *ngIf="current_user_details" [numStars]="5" [readOnly]="true" [ERROR 
            ->][value]="current_user_details.assignee_average_score"> </ion-rating> </ion-col> "): 
            ng:///app/src/pages/profile/profile.html@143:6 'ion-rating' is not a 
            known element: 1. If 'ion-rating' is an Angular component, then verify that it is part of this module. 2. If 
            'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this 
            component to suppress this message. (" </ion-col> <ion-col col-9> [ERROR ->]<ion-rating 
            *ngIf="current_user_details" [numStars]="5" [readOnly]="true" [value]="curren"): 
            ng:///app/src/pages/profile/profile.html@141:6 
Error: Template parse errors:
Can't bind to 'numStars' since it isn't a known property of 'ion-rating'.
1. If 'ion-rating' is an Angular component and it has 'numStars' input, then verify that it is part of this module.
2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <ion-col col-9 >
      <ion-rating *ngIf="current_user_details"
       [ERROR ->][numStars]="5" [readOnly]="true" 
       [value]="current_user_details.owner_average_score">
      </"): ng:///app/src/pages/profile/profile.html@131:7
Can't bind to 'readOnly' since it isn't a known property of 'ion-rating'.
1. If 'ion-rating' is an Angular component and it has 'readOnly' input, then verify that it is part of this module.
2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <ion-col col-9 >
      <ion-rating *ngIf="current_user_details"
       [numStars]="5" [ERROR ->][readOnly]="true" 
       [value]="current_user_details.owner_average_score">
      </ion-rating>
"): ng:///app/src/pages/profile/profile.html@131:22
Can't bind to 'value' since it isn't a known property of 'ion-rating'.
1. If 'ion-rating' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      <ion-rating *ngIf="current_user_details"
       [numStars]="5" [readOnly]="true" 
       [ERROR ->][value]="current_user_details.owner_average_score">
      </ion-rating>
    </ion-col>
"): ng:///app/src/pages/profile/profile.html@132:7
'ion-rating' is not a known element:
1. If 'ion-rating' is an Angular component, then verify that it is part of this module.
2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </ion-col>
    <ion-col col-9 >
      [ERROR ->]<ion-rating *ngIf="current_user_details"
       [numStars]="5" [readOnly]="true" 
       [value]="cur"): ng:///app/src/pages/profile/profile.html@130:6
Can't bind to 'numStars' since it isn't a known property of 'ion-rating'.
1. If 'ion-rating' is an Angular component and it has 'numStars' input, then verify that it is part of this module.
2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <ion-col col-9>
      <ion-rating *ngIf="current_user_details"
      [ERROR ->][numStars]="5" [readOnly]="true"
      [value]="current_user_details.assignee_average_score">
      <"): ng:///app/src/pages/profile/profile.html@142:6
Can't bind to 'readOnly' since it isn't a known property of 'ion-rating'.
1. If 'ion-rating' is an Angular component and it has 'readOnly' input, then verify that it is part of this module.
2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <ion-col col-9>
      <ion-rating *ngIf="current_user_details"
      [numStars]="5" [ERROR ->][readOnly]="true"
      [value]="current_user_details.assignee_average_score">
      </ion-rating>
"): ng:///app/src/pages/profile/profile.html@142:21
Can't bind to 'value' since it isn't a known property of 'ion-rating'.
1. If 'ion-rating' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      <ion-rating *ngIf="current_user_details"
      [numStars]="5" [readOnly]="true"
      [ERROR ->][value]="current_user_details.assignee_average_score">
      </ion-rating>
    </ion-col>
"): ng:///app/src/pages/profile/profile.html@143:6
'ion-rating' is not a known element:
1. If 'ion-rating' is an Angular component, then verify that it is part of this module.
2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </ion-col>
    <ion-col col-9>
      [ERROR ->]<ion-rating *ngIf="current_user_details"
      [numStars]="5" [readOnly]="true"
      [value]="curren"): ng:///app/src/pages/profile/profile.html@141:6
    at Error (native)
    at syntaxError (/app/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
    at TemplateParser.parse (/app/node_modules/@angular/compiler/bundles/compiler.umd.js:12041:19)
    at AotCompiler._compileComponent (/app/node_modules/@angular/compiler/bundles/compiler.umd.js:22867:39)
    at /app/node_modules/@angular/compiler/bundles/compiler.umd.js:22764:55
    at Array.forEach (native)
    at AotCompiler._compileSrcFile (/app/node_modules/@angular/compiler/bundles/compiler.umd.js:22748:20)
    at /app/node_modules/@angular/compiler/bundles/compiler.umd.js:22725:91
    at Array.map (native)
    at /app/node_modules/@angular/compiler/bundles/compiler.umd.js:22725:56
`

Any idea ?

**Comment by alexandretok** [comment]
Hmm, that's a little weird. I think I might know what it is. I'll try to fix it tonight'

Thanks for the info!

**Comment by betogrun** [comment]
Same issue here.

**Comment by alexandretok** [comment]
You can do this for a workaround:
In your app.module.ts import CUSTOM_ELEMENTS_SCHEMA like this:
`import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';`

and in the same file create a new array called `schemas` with it, like this:
```
imports: [...],
providers: [...],
...etc...
schemas: [CUSTOM_ELEMENTS_SCHEMA]
```

I believe it will work normally after this change.

**Comment by ser2131604** [comment]
Hi, I manage to make it work importing the component directly in the page im using it. nevertheless I need it in another page... and I cant have both import declarations.
I move it to the app.module.ts of the app and same error. 
I try with the CUSTOM_ELEMENTS_SCHEMA with no luck.

Im trying to add this component to the super starter proyect
-- ionic start xxxx super

Please some help would be apreciated..

**Comment by alexandretok** [comment]
@ser2131604 did you manage to get it working?

**Comment by ser2131604** [comment]
Hey, nop.. sorry but a switched to this https://www.npmjs.com/package/ionic2-rating
best luck

**Comment by hvallenilla** [comment]
Hi, I have the same problem, did you find the solution?
Best

**Comment by montaserfzy** [comment]
Hi!, The same issue.
